// TaskQuest Avatar Sprite Spec
// 24 wide × 28 tall, character-based palette
// . = transparent, e = outline, h = highlight, n = shadow
// Skin: k K j | Hair: b B r R y Y w W
// Cloth: d D u U g G p P l L t q | Metal: s S z | Gold: o O | Magic: c f m

window.SPRITE_SPEC = {
  warrior: {
    name: 'Warrior',
    tiers: ['Recruit','Footman','Sergeant','Champion','Warlord'],
    sprites: [
      // T1
      ["........................","........................","........eeeeee..........","..........e.............","......ebkkkkkbe.........","......ekkkkkkke.........","......eKkkkkkKe.........","......ekKkkkKke.........","......ekkkkke..........","........eeeee...........","........ekkke...........","......eddddde...........","......eddddddde.........","....edddddddde..........","....keddddddddek........","....ekedddddddel........","....ek.eddddde.l........","....e..eddddde.eL.......","......edddddE...........","......eUUEUUe...........","......eUUe.eUUe.........","......eUUe.eUUe.........","......eLLe.eLLe.........","......eLLe.eLLe.........","......eLLe.eLLe.........","....eLLLe.eLLLe.........","........................","........................"],
      // T2
      ["........................","........................","........eeeeee..........","......ebBbbBbe..........","......ebbkkkbbe.........","......ebkkkkkbe.........","......eKkkkkkKe.........","......ekKkkkKke.........","......ekkkkke..........","........eeeee...........","........ekkke....s......","......elllllesssss......","......elLLlLLleshSe.....","....ellLllLllesSe.......","....keLLLLLLLLekS.......","....elellllllelL........","....el.eLLLLLel.........","....e..elllllE..........","......eUUEUUe...........","......eUUEUUe...........","......eUUe.eUUe.........","......eUUe.eUUe.........","......eLLe.eLLe.........","......eLLe.eLLe.........","......eLLe.eLLe.........","....eLLLe.eLLLe.........","........................","........................"],
      // T3
      ["........................","........................","........eeeeee..........","......esSSSSse..........","......esShShSse.........","......esSSSSSse.........","......eKkkkkkKe.........","......ekKkkkKke.........","......ekkkkke......s....","........eeeee......shs..","........ekkke......shs..","..edDe.SSSSS....shs.....","..edDdesSSSSe...sSs.....","..edDdesSSSSe...sSs.....","..edDdesSSSSekssSsk.....","...eedDdesSSSSelSSSL....","...edDDdesSSSSe.SSL.....","...edDDde.SSSSE.........","...edDDde.SUSUS.........","...eedDde.UUEUU.........","....eddee.UUEUU.........","......eee.eUUe.eUUe.....","........eLLe.eLLe.......","........eLLe.eLLe.......","........eLLe.eLLe.......","......eLLLe.eLLLe.......","........................","........................"],
      // T4
      ["........................","........eeeeee..........","......eooOOoo.e.........","......eoOOoOOoOe........","......esSSSSSSse........","......esShShSSse........","......esSSSSSSse........","......eKkkkkkKe.........","......ekKkkkKke.........","......ekkkkke.....h.....","........eeeee.....shs...","........eSSSe.....sSs...","...eooe.sSSSs.....sSs...","...eoOoesSSSSe....sSs...","...eoOoesShShse...sSs...","...eoOoesSSSSse...sSs...","..eeoOoesSSSSse...sSs...","...eDDoesSSSSse...sSs...","...eDDoesSSSSse..ssSss..","...eDDoesSSSSse..LSSSL..","...eDDoe.SSSSS....SSL...","..eeoOoe.SUSUS....OL....","...eooee.UUEUU..........","......eee.eUUe.eUUe.....","........eSSe.eSSe.......","........eSSe.eSSe.......","......eLLLe.eLLLe.......","........................"],
      // T5
      [".....h..eeeeee....h.....","....hsh.eooooo.eh.shsh..","....sSseoOoOoOoesSs.....","....sSseohohohohesSs....","....sSseoOOOOOOoesSs....","....sseoSSSSSSoess......","......esShShSSse........","......esSSSSSSse........","......eKkkkkkKe.........","......eKkRRRkKe...f.....","......ekkkkke...fhf.....","........eeeee....fff....","........eSSSe....fff....","...eooe.sShSs....fSf....","...eoOoesSSSSe...fSf....","...eoOoesoooose..fSf....","...eoOoesoOoOse..fSf....","..eeoOoesShShse..fSf....","...eDDoesSSSSse..fSf....","...eDDoesSSSSse..fSf....","...eDDoesSSSSse.ofSfo...","...eDDoe.SSSSS..oSSSo...","..eeoOoe.SoSoS....SO....","....eooee.OUEUO....O.....","......eee.eUUe.eUUe.....","........eSSe.eSSe.......","........eSSe.eSSe.......","......eOOOe.eOOOe......."]
    ]
  },
  mage: {
    name: 'Mage',
    tiers: ['Apprentice','Acolyte','Conjurer','Sorcerer','Archmage'],
    sprites: [
      ["........................","........................","........eeeeee..........","......eByyyyBe..........","......eByyyyyyBe........","......ebkkkkkbe.........","......ekkkkkkke.........","......eKkkkkkKe.........","......ekKkkkKke.........","......ekkkkke..........","........eeeee...........","........ekkke...........","...l...epppppe..........","...el.eppppppe..........","...el.epppppppe.........","...el.eppppppppe........","...el.epppppppppk......","...el.eppppppppek......","...el.epppppppppe.......","...el.eppppppppe........","...el.epppppppe.........","...el.eppppppe..........","...el.eppppppe..........","...el.epppppppe.........","...el.epppppppe.........","...el.eeeeeeeee.........","...el...................","....e..................."],
      ["........................","........................","......epppppe...........","......epPPPPPpe.........","......eppPPPPpPe........","......eppkkkpppe........","......epkkkkkppe........","......epKkkkkKpe........","......epkKkkkKpe........","......eppkkkpe..........","........eppppe..........","........ekkke...........","...c...epppppe..........","..ccle.eppppppe.........","..ccl.epppppppee........","...el.eppppppppe........","...el.epppppppppk......","...el.eppppppppek......","...el.epppppppppe.......","...el.eppppppppe........","...el.eppppppe..........","...el.epppppe...........","...el.epppppe...........","...el.eppppppe..........","...el.epppppppe.........","...el.eeeeeeeee.........","...el...................","....e..................."],
      ["........................","......eppppe............","......epPPPPpe..........","......epPmPPPpe.........","......eppPPPPpe.........","......eppkkkppe.........","......epkkkkkppe........","......epKkkkkKpe........","......epkkkkpe..........","........epppppe.........","........ekkkkk..........","....cc.eooooooe.........","...ccche.opmpoe.........","...ccche.opmpoe.........","...ccche.eppppe.........","...cccheoppppppe........","....eche.ppppppe........","...el.epPPpPPpe.........","...el.epPpppPpek........","...el.eppppppppek......","...el.epPPpPPppe........","...el.eppppppppe........","...el.eppppppppe........","...el.epppPPPpe.........","...el.eppppppe..........","...el.eppppppe..........","...el.eooooooe..........","....e..................."],
      ["........................","......epppppee..........","....epPPPPPppe..........","....ePmPPmPmPpe.........","....eppPPPPPpPe.........","....eppkkkkkppe.........","....epkkkkkkkpe.........","....epKkkkkkKpe.........","....epWWkWWkWpe.........","......epWwwwwwwe........","......epwWWWWpe.........","......epwwwpe...........","....cce.kkkk.e..........","...cccceooooe...........","..cmccceopmpoe..........","..cmccceopmpoe..........","..cmccceopmpoe..........","...cccc.epppe...........","....eche.ppppppe........","...el.epPPpPPpe.........","...el.epPpcpPpek........","...el.eppcpcppppek.....","...el.epPPpPPppe........","...el.eppppppppe........","...el.eppppppppe........","...el.epppPPPpe.........","...el.eOOOOOOOe.........","....e..................."],
      ["....m...........m.......","...mmm.eooooooemmm......","...mhmeoOoOoOoOoemhm....","....meomOoOoOoOoOoem....","....meoOoOoOoOoOoOoe....","....epPPPPPPPPPpe.......","....ePmPPmPmPmPpe.......","....eppkkkkkkppe........","....epkkkkkkkpe.........","....epKkkkkkKpe.........","....epWWcWWcWpe.........","......epWwwwwwwe........","......epwWWWWpe.........","....cce.kkkk.e..........","...cccceeoooe...........","..cmcccceoOoe...........","..cmcmcceommoe..........","..cmcccceommoe..........","...cccceommmme..........","....cccceoOoe...........","....eche.ppppppe........","...el.eppccppppe........","...el.epcmcppppek......","...el.eppcppppppe.......","...el.eppppppppe........","...el.eppppppppe........","...el.eOOOOOOOe.........","....e..................."]
    ]
  },
  ranger: {
    name: 'Ranger',
    tiers: ['Scout','Hunter','Tracker','Pathfinder','Wildwarden'],
    sprites: [
      ["........................","........................","........eeeeee..........","......eyyyyye...........","......eyybbbye..........","......eybbbbbye.........","......eybkkkbye.........","......eKkkkkkKe.........","......ekKkkkKke.........","......ekkkkke..........","........eeeee...........","........ekkke...........","......eGGGGGe...........","......eGGGggGGe.........","....eGGggggGGe..........","....keGGggggggek........","....ekeGGGGGGgel........","....ek.eGGGGGe.l........","....e..eGGGGGe..........","......eLLeLLe...........","......eLLeLLe...........","......eLLe.eLLe.........","......eLLe.eLLe.........","......eLLe.eLLe.........","......eLLe.eLLe.........","....eLLLe.eLLLe.........","........................","........................"],
      ["........................","........................","........eeeeee..........","......eGGGGGGe..........","......eGGyyyGGe.........","......eGybbbyGe.........","......eybkkkbye.........","......eKkkkkkKe.........","......ekKkkkKke.........","......ekkkkke......l....","........eeeee......le...","........ekkke.....llel..","......eLLLLLe....lLel...","......eLLlllLLe..lLel...","....eLlllLLLLe...lLel...","....keLlLLLLLLek.lLel...","....ekeLLLLLLLel.lLel...","....ek.eLLLLLe.l.lLel...","....e..eLLLLLe...lLel...","......eLLeLLe....lLel...","......eLLeLLe.....le....","......eLLe.eLLe....l....","......eLLe.eLLe.........","......eLLe.eLLe.........","......eLLe.eLLe.........","....eLLLe.eLLLe.........","........................","........................"],
      ["........................","........eeeeee..........","......eGGGGGGe..........","......eGGGGGGGGe........","......eGybbbbyGe........","......eybkkkkbye........","......eKkkkkkKe.........","......ekKkkkKke.........","......ekkkkke......le...","........eeeee.....leel..","..gge...ekkke.....leel..","..gGge.eGGgGGe....lGel..","..gGge.eGggggGGe..lGel..","..gGge.eGggLLgGe..lGel..","..gGge.eGgLLLgGe..lGel..","..gGge.keGGgGGGek.lGel..","..gGge.ekeGGGGGel.lGel..","..gGGgeek.eGGGe.l.lGel..","..eGGge.e.eGGGe...lLel..","...eGGge..eLLLe...lLel..","....gGGe..eLLLe...lLel..","....gGGe.eLLe.eLLe.le...","....gGGe.eLLe.eLLe.l....","......gge.eLLe.eLLe.....","........eLLe.eLLe.......","......eLLLe.eLLLe.......","........................","........................"],
      ["........................","......eeeeeeeee.........","....eGGGGGGGGGe.........","....eGGGGGGGGGGe........","....eGGyybbyyGGe........","....eGybbkkbbyGe........","....eGyKkkkkkKye........","....eGekKkkkKkeGe.......","....eGGekkkkkeGGe..d....","....eGGeeeeeGGe...ddel..","......eGGekkkGe...ddel..","..gge.eGgGgGGGe..lddel..","..gGge.eGggggGGe.lddel..","..gGge.eGggLLgGe.lddel..","..gGge.eGggLLgGe.lddel..","..gGge.eGGgggGGe.lddel..","..gGgeekeggLLgek.lddel..","..gGGge.eGGGGGel.lddel..","..eGGge..eGGGGe.l.lddel.","...eGGge.elLLle...lddel.","....gGGe.elLLle...llLll..","....gGGeelLLeLLeel..ll..","....gGGe.LLeLLe.........","....egGe.LLeLLe.........","....eGGe.LLeLLe.........","....eGGee.LLeLLee.......","....eGGGe.eLLLLe........","........................"],
      ["..o.....eeeeee.....o....","..oo...eooe..eoo...oo...","...ooeoo.eGGGGe.ooeoo...","....eGGGGGGGGGGe........","....eGGGGGGGGGGe........","....eGGyybbyyGGe........","....eGybbkkbbyGe........","....eGyKkkckkKye........","....eGekKkkkKkeGe.......","....eGGekRRkkeGGe..d....","....eGGRRRRGGe....dde...","......eGRkkkRGe..lddel..","..gge.eGgGgGGGe..lddel..","..gGge.eGggcgGGe.lddel..","..gGge.eGgcLcgGe.lddel..","..gGge.eGgLcLgGe.lddel..","..gGge.eGggcggGe.lddel..","..gGgeekeggcgek..lddel..","..gGGge.eGGcGel..lddel..","..eGGge..eGcGe.l.lddel..","...eGGge.elcLle..lddel..","....gGGe.elLLle...llLll..","....gGGeelLLeLLeel..ll..","....gGGe.LLeLLe.........","....egGe.LLeLLe.........","....eGGee.LLeLLee.......","....eGGGe.eLLLLe........","........................"]
    ]
  },
  cleric: {
    name: 'Cleric',
    tiers: ['Initiate','Devotee','Priestess','Oracle','Saint'],
    sprites: [
      ["........................","........................","........eeeeee..........","......eyyyyyye..........","......eybbbbbye.........","......eybkkkbye.........","......eKkkkkkKe.........","......ekKkkkKke.........","......ekkkkke..........","........eeeee...........","........ekkke...........","......ewwwwwe...........","......ewwwwwwwe.........","....ewwwwwwwwe..........","....kewwwwwwwwwek.......","....ekewwwwwwwwel.......","....ek.ewwwwwwe.l.......","....e..ewwwwwwe.eL......","......ewwwwwwe..........","......ewweewwe..........","......ewwe.ewwe.........","......ewwe.ewwe.........","......eLLe.eLLe.........","......eLLe.eLLe.........","......eLLe.eLLe.........","....eLLLe.eLLLe.........","........................","........................"],
      ["........................","........................","........eeeeee..........","......eyyyyyye..........","......eybbbbbye.........","......eybkkkbye.........","......eKkkkkkKe.........","......ekKkkkKke.........","......ekkkkke......l....","........eeeee.....lol...","........ekkke....lohol..","......ewwwwwe....lohol..","......ewwwwwwwe..lohol..","....ewwwoooowwe..lohol..","....kewooooowwwekohel..","....ekewwooowwwelohol..","....ek.ewwowwwe.lohol..","....e..ewwwwwwe.eohol..","......ewwwwwwe...ohol..","......ewweewwe...ohol..","......ewwe.ewwe..ohol..","......ewwe.ewwe...le....","......eLLe.eLLe....l....","......eLLe.eLLe.........","......eLLe.eLLe.........","....eLLLe.eLLLe.........","........................","........................"],
      ["........................","........eeeeee..........","......eyyyyyyye.........","......eyybbbbyye........","......eybkkkkbye........","......eKkkkkkKye........","......ekKkkkKke.........","......ekkkkke......l....","........eeeee......lol..","........ekkke......lohol.","......eooooooe.....lohol.","......eowwwwwwoe...lohol.","......ewwwwwwwwe...lohol.","....ewwwwowwwwwe....lohol","....kewwwoooowwwekohol..","....ekewwwwowwwwelohol..","....ek.ewwwwowwwe.lohol.","....e..eowwwwwwoe..lohol","......ewwwwwwwwe...ohol.","......ewweEewwe....ohol.","......ewwoe.ewowe..ohol.","......ewwoe.ewowe..ohol.","......eLwoe.ewoLe...le..","......eLLe.eLLe.....l...","......eLLe.eLLe.........","....eLLLe.eLLLe.........","........................","........................"],
      ["........................","........eeeeee..........","......eOoOoOoe..........","......eyyhohyyye........","......eybbbbbye.........","......eybkkkkbye........","......eKkkkkkKye........","......ekKkkkKke.........","......ekkkkke......c....","........eeeee......cco..","........ekkke.....cohco.","......eooooooe....cohco..","......eowwwwwwoe..lohol..","......ewwwwwwwwe..lohol..","....ewwwoCowwwwe...lohol.","....kewwwoooowwwwkohol..","....ekewwwoCowwwelohol..","....ek.eowwwwwwoe.lohol.","....e..eowwwwwwoe..lohol","......ewwowwowe....ohol.","......ewwoEowwe....ohol.","......ewwoe.ewowe..ohol.","......ewwoe.ewowe..ohol.","......eLLoe.eLowe...le..","......eLLe.eLLe.....l...","....eLLLe.eLLLe.........","........................","........................"],
      ["......hhhhhhhh..........","......h.eeeeee.h........","....h.eOoOoOoe.h........","....h.eyyhohyyye.h......","...h..eybbbbbye...h.....","..h.h.eybkkkkbye.h.h....","..hwwh.eKkkkkkKye.hww...","..h.h.ekKkkkKke..h.h....","...h...ekkkkke....h.....","....h...eeeee.....c.....","........ekkke....ccc....","......eOoOoOoe...cohc...","......eowwhwwhoe..ohc...","......ewhWwwWwhe..ohc...","....ewhWohohwwwehohc....","....kewwhoOhowwwekohol..","....ekewwwoOowwwelohol..","....ek.eowhwwhwoe.lohol.","....e..eowwhwhwoe..lohol","......ewwhwwhwe....ohol.","......ewwoEowwe....ohol.","......ewwoe.ewowe..ohol.","......ewwoe.ewowe..ohol.","......eLLoe.eLowe...le..","......eLLe.eLLe.....l...","....eLLLe.eLLLe.........","........................","........................"]
    ]
  },
  rogue: {
    name: 'Rogue',
    tiers: ['Pickpocket','Footpad','Cutpurse','Shadowblade','Phantom'],
    sprites: [
      ["........................","........................","........eeeeee..........","......eUUUUUe...........","......eUUUUUUUe.........","......eUkkkkkUe.........","......eKkkkkkKe.........","......ekKkkkKke.........","......ekkkkke..........","........eeeee...........","........ekkke...........","......eUUUUUe...........","......eUUUUUUUe.........","....eUUUUUUUUe..........","....keUUUUUUUUek........","....ekeUUUUUUUel........","....ek.eUUUUUe.l........","....e..eUUUUUe..........","......eUUEUUe...........","......eUUEUUe...........","......eUUe.eUUe.........","......eUUe.eUUe.........","......eLLe.eLLe.........","......eLLe.eLLe.........","......eLLe.eLLe.........","....eLLLe.eLLLe.........","........................","........................"],
      ["........................","........................","........eeeeee..........","......eUUUUUe...........","......eUUUUUUUe.........","......eUkkkkkUe.........","......eKkkkkkKe.........","......ekKkkkKke.........","......ekkkkke..........","........eeeee...........","........ekkke...........","......eUUUUUe....s......","......eUUUUUUUe.shs.....","....eUUUUUUUUe..sLs.....","....keUUUUUUUUekL.......","....ekeUUUUUUUelL.......","....ek.eUUUUUe.l........","....e..eUUUUUe..........","......eUUEUUe...........","......eUUEUUe...........","......eUUe.eUUe.........","......eUUe.eUUe.........","......eLLe.eLLe.........","......eLLe.eLLe.........","......eLLe.eLLe.........","....eLLLe.eLLLe.........","........................","........................"],
      ["........................","........................","........eeeeee..........","......eUUUUUe...........","......eUUUUUUUe.........","......eUkkkkkUe.........","......eUeeeeeUe.........","......eKkkkkkKe.........","......ekKkkkKke.........","......ekkkkke..........","........eeeee......s....","..s.....ekkke.....shs...","..shs..eUUUUUe....sLs...","..sLs.eUUtttUUe...sLs...","..sLs.eUUttttUUe..sLs...","..sLskeUUttttUUek..L....","..sLselUUttttUUe..lL....","..sLsl.eUUtttUUe..l.....","..sLsl.eUUEUUe..........","..sLsl.eUUEUUe..........","...L..eUUe.eUUe.........","......eUUe.eUUe.........","......eLLe.eLLe.........","......eLLe.eLLe.........","......eLLe.eLLe.........","....eLLLe.eLLLe.........","........................","........................"],
      ["........................","........eeeeee..........","......eUUUUUe...........","......eUUUUUUUe.........","......eUkkkkkUe.........","......eUeeeeeUe.........","......eKkkkkkKe.........","......ekKkkkKke.........","......ekkkkke..........","........eeeee......c....","..tte...ekkke.....chc...","..tBte.eUUUUUe....cLc...","..tBte.eUUttttUe..cLc...","..tBte.eUtttttUe..cLc...","..tBte.eUttBttUe..cLc...","..tBteeeUttttttek..L....","..tBte.eUtttttel...L....","..tBte.eUttttttUe.......","..tBte.eUttBttUEe.......","..tBte.eUUEEEUUe........","..tBte.eUUe.eUUe........","..tBteeeUUe.eUUe........","..eBee.eLLe.eLLe........","......eLLe.eLLe.........","......eLLe.eLLe.........","....eLLLe.eLLLe.........","........................","........................"],
      ["..n.....eeeeee.....n....","..nBn...eUUUUUUe..nBn...","nBnBn.eUUUUUUUUe.nBnBn..","..nBn..eUkkkkkUe..nBn...","...n...eUeeeeeUe...n....","......eKkkRkkKe.........","......ekKkkkKke.........","......ekkkkke..........","........eeeee......c....","..cnc...ekkke.....chc...","..ctcc.eUUUUUe....cBc...","..ctc.eUUttttUe...cBc...","..ctc.eUtttBtttUe..cBc..","..ctc.eUttBcBttUe..cBc..","..ctc.eUtBcCcBtUe..cBc..","..ctc.eeUttBcttek..B....","..ctc..eUttBtttel..B....","..ctc..eUtBtBttUe.......","..ctc..eUtttBttUEe......","..ctc..eUUEEEEUUe.......","...c...eUUe.eUUe........","......eUUe.eUUe.........","...n...eLLe.eLLe...n....","..nBn..eLLe.eLLe..nBn...","..nBn..eLLe.eLLe..nBn...","..nBn.eLLLe.eLLLe.nBn...","...n...................n.","........................"]
    ]
  },
  bard: {
    name: 'Bard',
    tiers: ['Busker','Minstrel','Troubadour','Maestro','Songweaver'],
    sprites: [
      ["........................","........................","........eeeeee..........","......eyyyyye...........","......eyyyyyyye.........","......eyybbbyye.........","......eybkkkbye.........","......eKkkkkkKe.........","......ekKkkkKke.........","......ekkkkke..........","........eeeee...........","........ekkke......l....","......eddddde.....lll...","......eddqqqdde...lLLl..","....edqqqqqqde....lLLl..","....kedqqqqqqdek..lLl...","....ekeddqqqdde...llL...","....ek.edddddE.l...lL...","....e..eddEdde......l...","......eUUEUUe...........","......eUUEUUe...........","......eUUe.eUUe.........","......eUUe.eUUe.........","......eLLe.eLLe.........","......eLLe.eLLe.........","....eLLLe.eLLLe.........","........................","........................"],
      ["........................","........e...............","........eee.............","......eyyye.............","......eyyDyyye..........","......eyyDDDyye.........","......eyybbbyye.........","......eybkkkbye.........","......eKkkkkkKe.........","......ekKkkkKke.........","......ekkkkke......l....","........eeeee.....lll...","........ekkke.....lLLl..","......eddddde.....lLLl..","......edqqqqdde...lLLl..","....edqqOqqqde....lLLl..","....kedqOOOqqdek...lLl..","....ekedqOqqqdel...llL..","....ek.eddqqqde....lL...","....e..edddddde.....l...","......eUUEUUe...........","......eUUEUUe...........","......eUUe.eUUe.........","......eUUe.eUUe.........","......eLLe.eLLe.........","....eLLLe.eLLLe.........","........................","........................"],
      ["........................","........e...............","........eyy.............","......eyyyye............","......eyyDyyyye.........","......eyyDDDyye.........","......eyybbbyye.........","......eybkkkbye.........","......eKkkkkkKe.........","......ekKkkkKke.........","......ekkkkke..........","........eeeee...........","........ekkkk.....llll..","........eddddee..lLLLLl.","...lll.edqqqqdee..lLLLLl","..llLll.eqqOqqde..lLLLLl","..llLlleqOOOqdellLLLLl..","..llLLl.eqOqqqdellLLLLl.","...llLll.edqqqqdellLLLLl","....lll..edddddde.lLLLLl","....lll.eUUEUUe....llll.","...lll..eUUEUUe.........","......eUUe.eUUe.........","......eUUe.eUUe.........","......eLLe.eLLe.........","....eLLLe.eLLLe.........","........................","........................"],
      ["........................","........eee.............","......eyyyDyye..........","....eyyyDDDyye..........","....eyyDDhDDDyye........","....eyyDhDhDyyye........","....eyyyDDDyyyye........","....eyyybbbyyyye........","....eyybkkkkbyye........","....eyKkkkkkkKye........","....eyKkkkkkkKye........","....ekKkkkkKke..........","......ekkkkkke..........","......eeeeee............","........kkk........lllll","...lll.edddddee..lLLLLLl","..llLll.eooqqode..lLLLLLl","..llLlleeoOoOoodlLLLLLl.","..llLLleqOhOhqdlLLLLLl..","..llLLl.eqOOOOqde.lLLLLl","...llLll.eddqqqdde.lLLLLl","....lll..edddddde...lllll","....lll.eDDEDDe.........","......eDDe.eDDe.........","......eUUe.eUUe.........","......eLLe.eLLe.........","....eLLLe.eLLLe.........","........................"],
      ["....m.................m.","....mm..eeee.........mm.","...mhmeyyDDDDyye....mhm.","..m.meyyhDhDhDDyye..m..m","mhm.eyhDhDhDhDDDyyemhm..","..m.eyyhDhDhDhDhyyye..m.","....eyyDDDDDDyyye.......","....eyyybbbyyyye.......c","....eyybkkkkbyye......cc","....eyKkkkkkkKye.....cc.","....eyKkRkkRkKye....cc..","....ekKkkkkKke......c...","......ekkkkkke..........","......eeeeee......llll..","...llle.kkk.eee..lLLLLl.","..llLll.eOOOOoodlLLLLLl.","..llLlleeoOhOhoodlLLLLLl","..llLLleoOhmhOoodlLLLLLl","..llLLleeoOhOhOoodlLLLLLl","...llLll.eOOOOOOoo.LLLLLl","....lll..eOOOOOOoe..LLLLl","....lll.eDDEDDe.....llll.","....lll.eDDe.eDDe.......","......eUUe.eUUe.........","......eOOe.eOOe.........","....eOOOe.eOOOe.........","........................","........................"]
    ]
  }
};
